"use client";
import { FormEvent, ReactNode, useEffect, useRef, useState } from 'react';
import { experienceSettings as editorial } from '@/data/experience';
export function track(name:string){window.dispatchEvent(new CustomEvent('book:analytics',{detail:{event:name}}));}
export function TrackedLink({event,children,...props}:{event:string;children:ReactNode}&React.AnchorHTMLAttributes<HTMLAnchorElement>){return <a {...props} onClick={()=>track(event)}>{children}</a>;}
export function Experience(){useEffect(()=>{const update=()=>document.documentElement.classList.toggle('scrolled',window.scrollY>35);update();window.addEventListener('scroll',update,{passive:true});const target=document.getElementById('dimensions');let sent=false;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)&&!sent){track('seven_dimensions_viewed');sent=true;}},{threshold:.2});if(target)observer.observe(target);return()=>{window.removeEventListener('scroll',update);observer.disconnect();};},[]);return null;}
export function Nav(){const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);return <><button ref={toggle} className="menu-toggle" aria-label="Menu" aria-controls="main-nav" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button><nav id="main-nav" className={open?'nav open':'nav'} aria-label="Main navigation" onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}}}>{[['The book','#book'],['The 7 dimensions','#dimensions'],['The authors','#authors'],['Videos','#videos']].map(([t,h])=><a key={h} href={h} onClick={()=>setOpen(false)}>{t}</a>)}<a className="nav-join" href={editorial.primaryCta.href} onClick={()=>{track('join_community_clicked');setOpen(false);}}>Join the conversation <span>↗</span></a></nav></>;}
export function Media({id,name,url,transcript}:{id:string;name:string;url:string;transcript:string}){const dialog=useRef<HTMLDialogElement>(null);const trigger=useRef<HTMLButtonElement>(null);const [open,setOpen]=useState(false);return <><div className="media-controls"><button className="video-button" ref={trigger} disabled={!url} onClick={()=>{setOpen(true);dialog.current?.showModal();track(`author_video_${id}_played`);}}><span aria-hidden="true">▶</span>{url?'Watch welcome':'Welcome film coming soon'}</button><span className="duration">60–90 seconds</span></div><details className="transcript"><summary>Read video transcript</summary><p>{transcript||'The transcript will be published alongside the welcome film.'}</p></details><dialog ref={dialog} className="video-dialog" onKeyDown={e=>{if(e.key!=="Tab")return;const items=e.currentTarget.querySelectorAll<HTMLElement>("button, iframe, video");const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}} aria-label={`${name} welcome film`} onClose={()=>{setOpen(false);trigger.current?.focus();}} onClick={e=>{if(e.currentTarget===e.target)dialog.current?.close();}}><button className="close" autoFocus onClick={()=>dialog.current?.close()}>Close ×</button>{open&&(/\.(mp4|webm)(\?|$)/i.test(url)?<video controls playsInline src={url}/>:<iframe title={`${name} welcome film`} src={url} allow="fullscreen"/>)}</dialog></>;}
export function Cover(){const [failed,setFailed]=useState(false);return failed?<div className="cover-fallback"><span>From Splintered<br/>to Centered</span><small>Official cover coming soon</small></div>:<img src="/images/book-cover.png" alt="From Splintered to Centered, by Dr. Sanjiv Chopra and Dr. Loren Michaels Harris" width="700" height="1050" fetchPriority="high" onError={()=>setFailed(true)}/>;}
export function CommunityForm(){const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editorial.newsletterEndpoint){setStatus('Signup is not open yet. No details have been sent or saved.');return;}const form=e.currentTarget;const data=new FormData(form);setBusy(true);try{const r=await fetch(editorial.newsletterEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName:data.get('firstName'),email:data.get('email'),consent:true})});if(!r.ok)throw Error();setStatus('You’re subscribed. Thank you for joining the conversation.');track('newsletter_submitted');form.reset();}catch{setStatus('We could not complete your signup. Please try again.');}finally{setBusy(false);}}return <form onSubmit={submit}><p className="form-hint">{editorial.newsletterEndpoint?'A little room in your inbox for what matters.':'Email signup opens soon. This form does not send or save your details yet.'}</p><div className="form-fields"><label>First name<input name="firstName" autoComplete="given-name" required/></label><label>Email<input name="email" type="email" autoComplete="email" required/></label></div><label className="consent"><input type="checkbox" required/><span>By subscribing, you agree to receive updates related to the book. You may unsubscribe at any time.</span></label><button className="btn dark" disabled={busy} type="submit">{busy?'Joining…':'Join the Book Community'} <span>↗</span></button><p role="status" className="form-status">{status}</p></form>;}
