import { editorial as book } from '@/data/editorial';
import { dimensions } from '@/data/book';
import { CommunityForm, Cover, Experience, Media, Nav, TrackedLink } from './EditorialClient';
const Label=({children}:{children:React.ReactNode})=><p className="label">{children}</p>;
const Arrow=()=> <span aria-hidden="true">↗</span>;
export function EditorialPage(){return <><Experience/><a href="#content" className="skip-link">Skip to content</a><header className="header"><a href="#book" className="brand"><span className="brand-symbol" aria-hidden="true">◌</span><span>FROM SPLINTERED<br/><em>TO CENTERED</em></span></a><Nav/></header><main id="content">
<section className="editorial-hero" id="book"><div className="hero-grid"><div className="hero-copy"><Label>A new conversation about the soul</Label><h1>From Splintered<br/><em>to Centered</em></h1><p className="hero-subtitle">{book.subtitle}</p><p className="hero-authors">Dr. Sanjiv Chopra <span>&</span> Dr. Loren Michaels Harris</p><div className="hero-description"><p>{book.hook}</p><p><em>From Splintered to Centered</em> is an invitation to rediscover the relationship we may have neglected most: the relationship with the soul.</p></div><div className="hero-actions"><TrackedLink className="btn dark" href={book.primaryCta.href} event="hero_cta_clicked">{book.primaryCta.label}<Arrow/></TrackedLink><a className="text-link" href="#dimensions">Discover the Seven Dimensions ↓</a><a className="text-link" href="#authors">Meet the Authors ↗</a></div></div><figure className="editorial-cover"><div className="cover-orbits" aria-hidden="true"/><div className="cover-book"><Cover/></div><figcaption>A return to what has always been within you.</figcaption></figure></div><div className="hero-bottom"><p>Two journeys. Two voices.<br/><em>One invitation to come back to center.</em></p><a href="#videos">Turn the page <span>↓</span></a></div></section>
<section className="section welcome" id="videos"><div className="heading-row"><div><Label>01 / Meet the voices</Label><h2>Why We Wrote<br/><em>This Book</em></h2></div><p>Before you read their words, meet the two people behind the conversation.</p></div><div className="video-grid">{book.authors.map(a=><article className={`video-card ${a.id}`} key={a.id}><div className="video-portrait"><img src={a.portrait} alt={a.name} width={a.id==='sanjiv'?365:600} height={a.id==='sanjiv'?547:700} loading="lazy" referrerPolicy="no-referrer"/><span className="portrait-label">A welcome from {a.id==='sanjiv'?'Sanjiv':'Loren'}</span></div><div className="video-copy"><Label>{a.descriptor}</Label><h3>{a.name}</h3><p>{a.intro}</p><Media id={a.id} name={a.name} url={a.videoUrl} transcript={a.transcript}/></div></article>)}</div></section>
<section className="section recognition"><div><Label>02 / A familiar feeling</Label><h2>You Can Be Successful<br/><em>and Still Feel Far<br/>From Yourself</em></h2><p className="lead">You can build a career, raise a family, fill a calendar, earn recognition, and still sense that something essential has gone quiet.</p><blockquote>You may not have lost your soul.<br/><strong>You may have lost the conversation.</strong></blockquote></div><div className="recognition-list"><Label>Maybe you are…</Label>{book.recognition.map((s,i)=><p key={s}><span>{String(i+1).padStart(2,'0')}</span>{s}</p>)}<small>If any of these questions feel familiar, this book was written with you in mind.</small></div></section>
<section className="meditation"><img className="scene" src="/images/woodland-roots.webp" alt="" width="1536" height="1024" loading="lazy"/><div><Label>A moment of stillness</Label><blockquote>“The soul has not vanished.<br/><em>The connection has<br/>been neglected.</em>”</blockquote><span className="fine-rule"/></div></section>
<section className="section dimension-section" id="dimensions"><div className="heading-row"><div><Label>03 / Seven dimensions</Label><h2>One Journey<br/><em>Back to Center.</em></h2></div><p>The book is not a checklist for becoming perfect. It is a framework for noticing where we have become fragmented—and learning how to return.</p></div><div className="dimension-cards">{dimensions.map(([n,t,lead,copy])=><details className="dimension-card" key={n}><summary><span className="dimension-number">{n}</span><span className="dimension-name">{t}</span><span className="dimension-lead">{lead}</span><span className="expand" aria-hidden="true">+</span></summary><p>{copy}</p></details>)}</div><aside className="capstone"><Label>The capstone</Label><h3>Completion</h3><p>What happens when we stop measuring a life by applause and begin asking whether we lived, loved, served, forgave, and became what we were capable of becoming?</p><a href="#examination" className="text-link">Explore the journey <Arrow/></a></aside></section>
<section className="section two-voices" id="authors"><div className="heading-row"><div><Label>04 / The authors</Label><h2>One Question.<br/><em>Two Remarkably<br/>Different Journeys.</em></h2></div><p>Clarity and metaphor.<br/>Medicine and lived experience.<br/>Two voices in generous conversation.</p></div><div className="voices-grid">{book.authors.map((a,i)=><article key={a.id}><Label>0{i+1} / {a.name}</Label><blockquote>“{a.quote}”</blockquote><p>{a.voice}</p><TrackedLink className="text-link" href={`#${a.id}-story`} event="author_profile_clicked">Read his story <Arrow/></TrackedLink></article>)}</div><p className="conversation">Their answers are not always identical. That is precisely the point.<strong><em>From Splintered to Centered</em> is a conversation, not a sermon.</strong></p></section>
{book.authors.map((a,i)=><section className={`section story-section story-${a.id}`} id={`${a.id}-story`} key={a.id}><div className="story-heading"><Label>0{5+i} / A story of {i?'belonging':'calling'}</Label><h2>{a.storyTitle}</h2><span className="story-number" aria-hidden="true">{i?'II':'I'}</span></div><div className="story-prose">{a.story.map(p=><p key={p}>{p}</p>)}<blockquote>{a.conclusion}</blockquote><TrackedLink event="author_profile_clicked" href="#videos" className="text-link">Meet Dr. {i?'Loren':'Sanjiv'} <Arrow/></TrackedLink></div></section>)}
<section className="section reader-questions"><Label>07 / A book for the person who is asking…</Label>{book.questions.map((q,i)=><p key={q}><span>{String(i+1).padStart(2,'0')}</span>{q}</p>)}<footer>You do not need to have the answers before opening the book.<strong>The questions are where the journey begins.</strong></footer></section>
<section className="section book-practices"><div><Label>08 / Practical, not prescriptive</Label><h2>A Book to Reflect On—<br/><em>and a Book to Use.</em></h2><p><em>From Splintered to Centered</em> combines conversation, personal story, philosophical inquiry, medical perspective, spiritual reflection, and practical exercises.</p></div><div>{book.practices.map(([t,p],i)=><article key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{p}</p></div></article>)}</div></section>
<section className="section purpose"><div><Label>09 / A simple practice</Label><h2>What If Your Purpose<br/><em>Is Already Leaving Clues?</em></h2></div><div>{book.purpose.map((p,i)=><p key={p}><span>0{i+1}</span>{p}</p>)}<blockquote>Your purpose may already be lurking there.</blockquote><TrackedLink href="#join" className="btn light" event="join_community_clicked">Get Book Updates <Arrow/></TrackedLink></div></section>
{book.eventsEnabled&&<aside className="campaign-interlude"><div><Label>Beyond the pages</Label><h2>Centered <em>Voices.</em></h2><a className="text-link" href="#event">Meet the special episode guests <Arrow/></a></div><img src="/images/centered-voices-banner.jpeg" alt="Centered Voices — a Bathrobe Moments television special inspired by the book" width="1600" height="595" loading="lazy"/></aside>}
<section className="section legacy"><Label>10 / A different accounting</Label><h2>The Soul<br/><em>Measures Differently.</em></h2><div className="measure-grid"><article><Label>The world may ask</Label>{book.world.map(p=><p key={p}>{p}</p>)}</article><article><Label>The soul may ask</Label>{book.soul.map(p=><p key={p}>{p}</p>)}</article></div><blockquote>“{book.wealthQuote.text}”</blockquote></section>
<section className="section third-act"><div><Label>11 / The third act</Label><h2>Your Next Chapter<br/><em>May Be Your<br/>Most Important One.</em></h2><p>There comes a point when achievement begins giving way to transmission. You stop asking only, “What can I accomplish?” And begin asking:</p><blockquote>“What can I give away?”</blockquote></div><div className="gifts">{book.gifts.map((g,i)=><p key={g}><span>0{i+1}</span>{g}</p>)}<small>The third act is not necessarily about winding down. It may be the season in which a lifetime finally becomes useful to someone else.</small></div></section>
<section className="section relationships"><div className="relationship-rings" aria-hidden="true"><i/><i/></div><div><Label>12 / Recognition & relationship</Label><h2>To Be Recognized<br/><em>Is Different<br/>From Being Chosen.</em></h2><p>The book explores kindred souls, friendship, marriage, loneliness, emotional safety, connection, and love as stewardship.</p><blockquote>Do not only search for “the one.” Become the person who can be recognized by the love you seek.</blockquote></div></section>
{book.soulLibraryEnabled&&<section className="section soul-library" id="library"><div className="heading-row"><div><Label>13 / The Soul Library</Label><h2>A Conversation<br/><em>Across Centuries.</em></h2></div><p>The soul has been speaking through human culture for centuries. A future companion archive will explore the works that help us hear it.</p></div><div className="library-shelves">{book.library.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Curated works & reflections</p></article>)}</div><TrackedLink href="#join" className="text-link" event="soul_library_clicked">Soul Library — coming soon. Receive updates <Arrow/></TrackedLink></section>}
<section className="section examination" id="examination"><div><Label>A quiet inventory</Label><h2>The Soul<br/><em>Examination.</em></h2><p>Not a score. Not a verdict.<br/>An invitation to notice.</p></div><div>{book.inventory.map((q,i)=><details key={q}><summary><span>0{i+1}</span>{q}<i>+</i></summary><p>Pause with this question. What moment from your day comes to mind?</p></details>)}</div></section>
{book.eventsEnabled&&<section className="section event" id="event"><div className="heading-row"><div><Label>A special conversation</Label><h2>Five Guests.<br/><em>One Powerful Conversation.</em></h2></div><p>Jason Sisneros · Joseph Michelli, Ph.D.<br/>Maureen Flatley · Dennis Bonilla · Elle Ullman<br/>With Dr. Loren and Dr. Sanjiv</p></div><a href="/images/centered-voices-event.jpeg" target="_blank" rel="noreferrer"><img src="/images/centered-voices-event.jpeg" alt="Centered Voices special episode guest lineup, with Dr. Loren Michaels Harris and Dr. Sanjiv Chopra" width="1600" height="898" loading="lazy"/></a><p className="art-caption">Real conversations. Deeper insights. A more centered you. <a href="/images/centered-voices-event.jpeg" target="_blank" rel="noreferrer">View full size ↗</a></p></section>}
<section className="final-invitation"><img src="/images/woodland-glade.webp" className="scene" alt="" width="1536" height="1024" loading="lazy"/><div><Label>An invitation to return</Label><h2>The Music Is<br/><em>Still Within You.</em></h2><div className="closing-lines">{book.closing.map(p=><p key={p}>{p}</p>)}</div><blockquote>Centered does not mean untouched.<br/><em>It means returnable.</em></blockquote><TrackedLink className="btn light" href="#join" event="join_community_clicked">Begin the Journey <span>↓</span></TrackedLink></div></section>
<section className="section community" id="join"><div><Label>Stay connected</Label><h2>Join the<br/><em>Conversation.</em></h2><p>Receive book updates, behind-the-scenes conversations with Dr. Sanjiv and Dr. Loren, launch announcements, reflections, and new material from the world of <em>From Splintered to Centered.</em></p>{book.links.preorder&&<TrackedLink event="preorder_clicked" href={book.links.preorder} className="text-link">Preorder <Arrow/></TrackedLink>}{book.links.buy&&<a href={book.links.buy} className="text-link">Buy the Book <Arrow/></a>}{book.links.media&&<a href={book.links.media} className="text-link">Media / Speaking <Arrow/></a>}</div><CommunityForm/></section>
</main><footer className="editorial-footer"><div><a href="#book" className="footer-title">From Splintered<br/><em>to Centered</em></a><p>{book.subtitle}</p><small>Dr. Sanjiv Chopra & Dr. Loren Michaels Harris</small></div><nav aria-label="Footer">{[['The Book','#book'],['Seven Dimensions','#dimensions'],['Authors','#authors'],['Videos','#videos'],...(book.soulLibraryEnabled?[['Soul Library','#library']]:[]),['Updates','#join'],['Contact',book.links.contact],['Privacy','#privacy']].map(([t,h])=><a href={h} key={t}>{t}</a>)}{book.socials.map(s=><a href={s.href} key={s.label}>{s.label}</a>)}</nav><div className="legal" id="privacy"><p>This book and website are intended for educational and inspirational purposes and are not substitutes for individualized medical, psychological, psychiatric, or other professional care.</p><p>No newsletter data is collected while signup is unconfigured. {book.crisisResourceCopy}</p><small>© {new Date().getFullYear()} From Splintered to Centered</small></div></footer></>;}
