import { dimensions, siteConfig } from "@/data/book";
import { Newsletter, VideoButton } from "./ClientBits";

export const Mark = () => <span className="mark" aria-hidden="true">✺</span>;
export const Eyebrow = ({children}:{children:React.ReactNode}) => <p className="eyebrow">{children}</p>;
export function Scenery({name, eager=false}:{name:string;eager?:boolean}) { return <picture className="scenery" aria-hidden="true"><source media="(max-width: 700px)" srcSet={`/images/${name}-mobile.webp`}/><img src={`/images/${name}.webp`} alt="" width="1536" height="1024" loading={eager?"eager":"lazy"} fetchPriority={eager?"high":"auto"}/></picture>; }

export function Hero(){return <section className="hero" id="book"><Scenery name="woodland-hero" eager/><div className="hero-shade"/><div className="sunlight" aria-hidden="true"/><div className="hero-copy"><Eyebrow>A journey back to yourself</Eyebrow><h1>From Splintered<br/><em>to Centered</em></h1><p className="subtitle">7 Dimensions for Navigating Your Soul</p><p className="byline">Dr. Sanjiv Chopra <span>&</span> Dr. Loren Michaels Harris</p><p className="hero-intro">Beyond achievement. Beneath the noise.<br/>A more meaningful life is taking root.</p><a href="#dimensions" className="button">Explore the seven dimensions <span>↗</span></a><a href="#authors" className="quiet-link">Meet the two voices behind the book</a></div><figure className="book-stage"><div className="physical-book"><img src={siteConfig.images.cover} alt="From Splintered to Centered — book cover by Dr. Sanjiv Chopra and Dr. Loren Michaels Harris" width="700" height="1050" fetchPriority="high"/></div><figcaption>Two journeys. One invitation to come back to center.</figcaption></figure><a className="scroll-cue" href="#journey">Let the journey unfold <span>↓</span></a></section>;}

export function Journey(){return <section className="journey" id="journey"><Scenery name="woodland-roots"/><div className="journey-copy"><Eyebrow>01 / The return</Eyebrow><h2>You haven’t lost yourself.<br/><em>You’re finding your way back.</em></h2><p>You can build a career, fill a calendar, and be surrounded by people—and still feel far from yourself.</p><p><em>From Splintered to Centered</em> invites you to rediscover the relationship beneath it all: the relationship with your soul.</p><blockquote>“The soul has not vanished.<br/>The connection has been neglected.”</blockquote></div></section>;}

export function Dimensions(){return <section className="dimensions paper" id="dimensions"><header><Eyebrow>02 / The framework</Eyebrow><h2>Seven dimensions.<br/><em>One living journey.</em></h2><p>Not a checklist for becoming perfect. A way to notice what matters—and gently return to it.</p><span className="botanical-mark" aria-hidden="true">❧</span></header><div className="dimension-list">{dimensions.map(([n,title,lead,copy])=><details key={n}><summary><span className="number">{n}</span><span><strong>{title}</strong><small>{lead}</small></span><span className="disclosure" aria-hidden="true">+</span></summary><p>{copy}</p></details>)}<p className="completion"><span>The capstone: Completion.</span> A life measured by what we lived, loved, served, and became.</p></div></section>;}

export function Authors(){return <section className="authors-section" id="authors"><header className="section-heading"><Eyebrow>03 / The authors</Eyebrow><h2>Two lives.<br/><em>One extraordinary conversation.</em></h2><p>Different paths to the same question: what makes a human life deeply meaningful?</p></header><div className="authors-grid"><article className="author"><div className="author-identity portrait sanjiv-portrait"><img src={siteConfig.images.sanjiv} alt="Dr. Sanjiv Chopra smiling in a navy suit and gold tie" width="365" height="547" loading="lazy"/></div><div className="author-copy"><span className="eyebrow">Medicine, meaning & a life of service</span><h3>Dr. Sanjiv Chopra</h3><p>Decades in medicine, teaching, meditation, and friendship led Sanjiv beyond the question of success toward the deeper experience of fulfillment.</p><details><summary>Read Sanjiv’s story <span>+</span></summary><p>As Sanjiv recalls in the book, at twelve years old he woke from a nap and discovered that he could not see. His father, a cardiologist hundreds of miles away, identified what he believed was a rare reaction and urged immediate treatment.</p><p>The next morning, Sanjiv could see. The experience became a calling: he wanted to become a healer.</p></details><VideoButton author="Sanjiv" url={siteConfig.authors.sanjiv.videoUrl}/></div></article><article className="author"><div className="author-identity portrait"><img src={siteConfig.images.loren} alt="Dr. Loren Michaels Harris smiling and tipping his hat" width="600" height="700" loading="lazy" referrerPolicy="no-referrer"/></div><div className="author-copy"><span className="eyebrow">Belonging, courage & listening within</span><h3>Dr. Loren Michaels Harris</h3><p>Adoption, foster care, creativity, and the search for his birth family became an unexpected education in belonging—and in listening to the voice within.</p><details><summary>Read Loren’s story <span>+</span></summary><p>After years pursuing music, the opportunity Loren had worked toward was becoming real. Then something called more loudly: the need to search for his birth mother.</p><p>Walking away looked irrational from the outside. From within, it was necessary. Achievement and fulfillment had stopped being the same destination.</p></details><VideoButton author="Loren" url={siteConfig.authors.loren.videoUrl}/></div></article></div></section>;}

export function CenteredVoices(){return <section className="centered-voices" id="centered-voices"><div className="special-intro"><div><Eyebrow>04 / Beyond the pages · Bathrobe Moments</Eyebrow><h2>Centered <em>Voices.</em></h2></div><p>Extraordinary people. Real stories.<br/>A conversation that keeps growing.</p></div><figure><img src="/images/centered-voices-banner.jpeg" alt="Centered Voices, a 90-minute Bathrobe Moments television special inspired by From Splintered to Centered" width="1600" height="595" loading="lazy"/></figure><div className="special-footer"><p>A collective conversation to<br/><em>inspire, heal, and ignite change.</em></p><a className="button outline" href="#event">Explore the special episode <span>↓</span></a></div></section>;}

export function EventBanner(){return <section className="centered-voices event-section" id="event"><div className="special-intro"><div><Eyebrow>06 / The special episode</Eyebrow><h2>Five guests.<br/><em>One powerful conversation.</em></h2></div><p>Meet the voices joining<br/>Dr. Loren and Dr. Sanjiv.</p></div><figure><img src="/images/centered-voices-event.jpeg" alt="Centered Voices event featuring Jason Sisneros, Joseph Michelli, Ph.D., Maureen Flatley, Dennis Bonilla, Elle Ullman, Dr. Loren Michaels Harris, and Dr. Sanjiv Chopra" width="1600" height="898" loading="lazy"/></figure><div className="special-footer"><p>Real conversations. Deeper insights.<br/><em>A more centered you.</em></p><a className="button outline" href="/images/centered-voices-event.jpeg" target="_blank" rel="noreferrer">View event banner full size <span>↗</span></a></div></section>;}

export function Living(){return <section className="living paper" id="practice"><header className="section-heading"><Eyebrow>05 / Beyond reading</Eyebrow><h2>A book to sit with.<br/><em>A way to live.</em></h2></header><div className="practices-grid"><article><span className="number">I.</span><h3>Notice what nourishes you.</h3><p>For thirty days, record three or four meaningful activities and rate the experience from one to ten. Look for the moments that repeatedly bring joy, energy, and meaning. Your purpose may already be leaving clues.</p></article><article><span className="number">II.</span><h3>Make room for connection.</h3><p>Practice gratitude, forgiveness, and listening. Friendship, love, and emotional safety grow through attention. Do not only search for someone who recognizes you; become someone who can recognize and care for others.</p></article><article><span className="number">III.</span><h3>Plant what can outlive you.</h3><p>Share wisdom, courage, time, and opportunity. Your next chapter may be less about what you can accomplish and more about what you can give away. The soul measures a life through love, truth, and service.</p></article></div><details className="reflection"><summary><span>A quiet moment: the soul examination</span><span className="disclosure">+</span></summary><p>No score. No verdict. Take one question with you today.</p><div>{["Did I notice?","Did I align?","Did I listen?","Did I integrate?","Did I serve?","Did I nourish?","Did I plant?","Did I return?"].map(q=><p key={q}>{q}</p>)}</div></details></section>;}

export function Invitation(){return <section className="invitation" id="join"><Scenery name="woodland-glade"/><div className="invitation-content"><Eyebrow>07 / An invitation to return</Eyebrow><h2>The music is<br/><em>still within you.</em></h2><blockquote>Centered does not mean untouched.<br/>It means returnable.</blockquote><p>Book updates, reflections, and conversations with Dr. Sanjiv and Dr. Loren. A little space for what matters.</p><Newsletter/></div></section>;}
