import { dimensions, questions, recognition, siteConfig } from "@/data/book";
import { Newsletter, VideoButton } from "./ClientBits";

export const Mark = ({ light=false }: { light?: boolean }) => <div className={`mark ${light ? "light" : ""}`} aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /><span /></div>;
export const Eyebrow = ({ children }: { children: React.ReactNode }) => <p className="eyebrow">{children}</p>;

export function Hero() { return <section className="hero" id="book"><div className="hero-copy"><Eyebrow>A new conversation about the soul</Eyebrow><h1>From Splintered<br /><em>to</em> Centered</h1><p className="subtitle">7 Dimensions for Navigating Your Soul</p><p className="authors">Dr. Sanjiv Chopra <span>&amp;</span> Dr. Loren Michaels Harris</p><div className="rule" /><p className="lede">We live in an age of extraordinary connection, achievement, information, and speed. Yet many of us feel more fragmented, lonely, and uncertain about what our lives mean.</p><p><em>From Splintered to Centered</em> is an invitation to rediscover the relationship we may have neglected most: the relationship with the soul.</p><div className="actions"><a className="button" href="#dimensions">Discover the Seven Dimensions <span>↓</span></a><a className="text-link" href="#authors">Meet the Authors <span>→</span></a></div><p className="support">Two journeys. Two voices. One invitation to come back to center.</p></div><div className="cover-wrap"><div className="cover" role="img" aria-label="Official book cover placeholder"><Mark light/><div><small>FROM</small><strong>SPLINTERED</strong><small>TO</small><strong>CENTERED</strong><hr/><p>7 Dimensions for<br/>Navigating Your Soul</p></div><footer>DR. SANJIV CHOPRA<br/>DR. LOREN MICHAELS HARRIS</footer></div><p className="asset-note">Official cover artwork coming soon</p></div><a className="scroll" href="#videos" aria-label="Scroll to welcome videos">Scroll to discover <span>↓</span></a></section> }

export function Welcome() { return <section className="section welcome" id="videos"><header className="section-head"><Eyebrow>Two authors · Two welcome films</Eyebrow><h2>Why We Wrote<br/>This Book</h2><div><p>Before you read their words, meet the two people behind the conversation.</p><span className="film-meta">Two films · 60–90 seconds each · Captions &amp; transcripts</span></div></header><div className="video-grid">{Object.entries(siteConfig.authors).map(([id,a], i) => <article className={`video-card tone-${i}`} key={id}><div className="portrait-placeholder"><span>{i ? "LMH" : "SC"}</span>{a.posterImage && <img src={a.posterImage} alt={`Portrait of ${a.name}`} loading="lazy" referrerPolicy="no-referrer" />}<Mark light /><div className="video-badge">Welcome film · 0{i+1}</div></div><div className="video-copy"><span className="count">Author 0{i+1}</span><h3>{a.name}</h3><b>{a.descriptor}</b><p>{i ? "After a lifetime of searching for family, belonging, meaning, and purpose, Loren discovered that one of the voices he sought had been speaking from within all along." : "After decades in medicine, education, and leadership, Sanjiv began asking a different question: what makes a life not merely successful, but deeply fulfilled?"}</p><VideoButton author={id} url={a.videoUrl}/><details><summary>Read video transcript</summary><p>Transcript will be published alongside the welcome video.</p></details></div></article>)}</div></section> }

export function Recognition() { return <section className="section recognition"><div><Eyebrow>Does this feel familiar?</Eyebrow><h2>You Can Be Successful<br/>and Still Feel Far<br/>From Yourself</h2><p className="big-copy">You can build a career, raise a family, fill a calendar, earn recognition, and still sense that something essential has gone quiet.</p><blockquote>You may not have lost your soul.<br/><strong>You may have lost the conversation.</strong></blockquote></div><div className="maybe"><span>Maybe you are…</span>{recognition.map((x,i)=><p key={x}><i>{String(i+1).padStart(2,"0")}</i>{x}</p>)}</div></section> }

export function QuoteBreak() { return <section className="quote-break"><Mark light/><blockquote>“The soul has not vanished.<br/><em>The connection has been neglected.</em>”</blockquote></section> }

export function Dimensions() { return <section className="section dimensions" id="dimensions"><header><Eyebrow>The framework</Eyebrow><h2>Seven Dimensions.<br/><em>One Journey Back to Center.</em></h2><p>The book is not a checklist for becoming perfect. It is a framework for noticing where we have become fragmented—and learning how to return.</p></header><div className="dimension-list">{dimensions.map(([n,t,lead,copy])=><details key={n}><summary><span>{n}</span><h3>{t}</h3><b>{lead}</b><i>＋</i></summary><p>{copy}</p></details>)}</div><aside className="capstone"><span>The capstone</span><h3>Completion</h3><p>What happens when we stop measuring a life by applause and begin asking whether we lived, loved, served, forgave, and became what we were capable of becoming?</p><a className="text-link" href="#examination">Explore the journey <span>→</span></a></aside></section> }

export function Voices() { return <section className="voices" id="authors"><header><Eyebrow>The authors</Eyebrow><h2>One Question.<br/>Two Remarkably<br/>Different Journeys.</h2></header><div className="voice sanjiv"><span>01 / Sanjiv</span><blockquote>“Achievement and fulfillment are not necessarily the same thing.”</blockquote><p>Medicine taught him how extraordinary the human body is. Decades of teaching, friendship, meditation, travel, service, and reflection led him toward another question: what makes a human life deeply meaningful?</p><a href="#sanjiv">Read his story →</a></div><div className="voice loren"><span>02 / Loren</span><blockquote>“I spent years looking everywhere for something that had been speaking from inside me the entire time.”</blockquote><p>His journey through adoption, foster care, creativity, searching for his birth family, love, intuition, and service became an unexpected education in listening.</p><a href="#loren">Read his story →</a></div><p className="conversation">Their answers are not always identical. That is precisely the point.<strong><em>From Splintered to Centered</em> is a conversation, not a sermon.</strong></p></section> }

export function Stories() { return <><section className="story" id="sanjiv"><div className="story-art indigo"><span>SC</span><div className="orbit"/></div><div className="story-copy"><Eyebrow>A story of calling</Eyebrow><h2>The Moment a Twelve-Year-Old Found His Calling</h2><p>As Sanjiv recalls in the book, at twelve years old he woke from a short nap and discovered that he could not see. Physicians struggled to explain it. His father, a cardiologist hundreds of miles away, began asking questions.</p><p>Through a remarkable sequence of medical reasoning, his father identified what he believed was a rare reaction and urged immediate treatment.</p><p>The following morning, Sanjiv opened his eyes. He could see. And something inside the twelve-year-old had changed.</p><strong>He wanted to become a healer.</strong></div></section><section className="story reverse" id="loren"><div className="story-art terra photo-art"><span>LMH</span><img src={siteConfig.images.loren} alt="Dr. Loren Michaels Harris smiling and tipping his hat" loading="lazy" referrerPolicy="no-referrer" /></div><div className="story-copy"><Eyebrow>A story of belonging</Eyebrow><h2>Sometimes the Dream You Leave Is Not the Dream You Lose</h2><p>Loren had spent years pursuing music. The opportunity he had worked toward was becoming real. And then something unexpected began calling more loudly than the dream he thought he wanted: the need to search for his birth mother.</p><p>Walking away looked irrational from the outside. From the inside, it was becoming necessary.</p><p>Years later, he would understand that moment differently:</p><strong>Achievement and fulfillment had stopped being the same destination.</strong></div></section></> }

export function ReaderQuestions() { return <section className="reader-questions"><Eyebrow>This book is for the person who is asking…</Eyebrow>{questions.map((q,i)=><p key={q}><span>{String(i+1).padStart(2,"0")}</span>{q}</p>)}<footer>You do not need to have the answers before opening the book.<strong>The questions are where the journey begins.</strong></footer></section> }

const practices = [["Reflection Questions","Slow down long enough to hear your own answers."],["Soul Practices","Simple exercises in awareness, gratitude, forgiveness, relationships, and service."],["Purpose Discovery","A thirty-day exercise for noticing what consistently produces joy and meaning."],["The Soul’s Final Inventory","Questions about courage, truth, love, service, and possibility."],["Visual Meditations","Full-page experiences designed to be contemplated, not simply skimmed."]];
export function Practices() { return <section className="section practices"><header><Eyebrow>Practical, not prescriptive</Eyebrow><h2>A Book to Reflect On —<br/><em>and a Book to Use</em></h2><p><em>From Splintered to Centered</em> combines conversation, personal story, philosophical inquiry, medical perspective, spiritual reflection, and practical exercises.</p></header><div>{practices.map((p,i)=><article key={p[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{p[0]}</h3><p>{p[1]}</p></article>)}</div></section> }

export function PurposeLegacy() { return <><section className="purpose"><div><Eyebrow>A simple practice</Eyebrow><h2>What If Your Purpose Is Already Leaving Clues?</h2></div><div><p>For thirty days, write down three or four meaningful activities from your day. Rate each from 1 to 10 based on the experience it created in you.</p><p>At the end of the month, look closely at the moments that repeatedly produced joy, energy, engagement, or even glimpses of bliss.</p><blockquote>Your purpose may already be lurking there.</blockquote><a href="#join" className="button pale">Get book updates →</a></div></section><section className="legacy"><Eyebrow>A different accounting</Eyebrow><h2>The Soul Measures Differently</h2><div className="measure"><article><h3>The world may ask</h3>{["What did you earn?","What did you achieve?","What title did you hold?","Who recognized you?","How far did you rise?"].map(x=><p key={x}>{x}</p>)}</article><article><h3>The soul may ask</h3>{["Did you love?","Did you serve?","Did you forgive?","Did you tell the truth?","Did you help someone else rise?","Did you live your purpose?"].map(x=><p key={x}>{x}</p>)}</article></div><blockquote>“True wealth is what fortunes cannot forge and death cannot diminish.”</blockquote></section></> }

export function LaterLife() { return <section className="section later"><div><Eyebrow>The third act</Eyebrow><h2>Your Next Chapter May Be Your Most Important One</h2><p>There comes a point when achievement begins giving way to transmission. You stop asking only, “What can I accomplish?” and begin asking:</p><blockquote>“What can I give away?”</blockquote></div><div className="gifts">{["Wisdom","Courage","Experience","Perspective","Opportunity","Time","Talent","Treasure"].map((x,i)=><span key={x}>{String(i+1).padStart(2,"0")} — {x}</span>)}<p>The third act is not necessarily about winding down. It may be the season in which a lifetime finally becomes useful to someone else.</p></div></section> }

export function RelationshipsLibrary() { return <><section className="relationships"><Mark/><div><Eyebrow>Recognition & relationship</Eyebrow><h2>To Be Recognized Is Different From Being Chosen</h2><p>The book explores kindred souls, friendship, marriage, loneliness, emotional safety, connection, and love as stewardship.</p><blockquote>Do not only search for “the one.” Become the person who can be recognized by the love you seek.</blockquote></div></section>{siteConfig.soulLibraryEnabled && <section className="section library" id="library"><header><Eyebrow>Coming soon</Eyebrow><h2>The Soul Has Been Speaking Through Human Culture for Centuries</h2><p>A curated companion archive exploring how the soul appears across the art and ideas that shape us.</p></header><div>{["Books & Poetry","Music & Film","Art & Philosophy","Faith & Spirituality"].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Curated works and reflections</p></article>)}</div><button disabled>Explore the Soul Library — Coming Soon</button></section>}</> }

export function Examination() { return <section className="examination" id="examination"><div><Eyebrow>A quiet inventory</Eyebrow><h2>The Soul<br/>Examination</h2><p>Not a score. Not a verdict.<br/>An invitation to notice.</p></div><div>{["Did I notice?","Did I align?","Did I listen?","Did I integrate?","Did I serve?","Did I nourish?","Did I plant?","Did I return?"].map((x,i)=><p key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</p>)}</div></section> }

export function FinalInvitation() { return <section className="final-invite"><Mark light/><Eyebrow>An invitation to return</Eyebrow><h2>The Music Is<br/>Still Within You.</h2><div className="still">{["listen.","repair.","forgive.","serve.","say what needs to be said.","become more fully yourself.","plant something another person may one day sit beneath."].map(x=><p key={x}>There is still time to <strong>{x}</strong></p>)}</div><blockquote>Centered does not mean untouched.<br/><em>It means returnable.</em></blockquote><a className="button pale" href="#join">Begin the Journey <span>↓</span></a></section> }

export function Join() { return <section className="join" id="join"><div><Eyebrow>Stay connected</Eyebrow><h2>Join the<br/>Conversation</h2></div><div><p>Receive book updates, behind-the-scenes conversations with Dr. Sanjiv and Dr. Loren, launch announcements, reflections, and new material from the world of <em>From Splintered to Centered.</em></p><Newsletter/></div></section> }
